Auth page
dev-sect/ScheduleDevelopmentKit-frontend pull request #12
Opened 2022-01-17 11:46 UTC by Aleksey-Levin

2022-01-20 13:44 UTC, sashafromlibertalia requested changes
сделай так чтобы тесты прошли пж

2022-01-20 13:44 UTC, sashafromlibertalia commented on src/pages/Auth.vue
> +    <div class="leftPart">
названия классов чот не оч. Припиши, что это относится к окну авторизации

2022-01-20 13:44 UTC, sashafromlibertalia commented on src/pages/Main.vue
> +  <div class="leftPart">
тот же топик с классами

2022-01-22 00:12 UTC, Aleksey-Levin commented
но крч пока не нада мёрджить, ибо я ещё залью версию с чекбоксом завтра... или послезавтра

2022-01-22 06:08 UTC, sashafromlibertalia requested changes

2022-01-22 06:08 UTC, sashafromlibertalia commented on src/pages/Main.vue
> +  <div class=""></div>
а че тут пустой класс делает

2022-01-22 06:08 UTC, sashafromlibertalia commented on src/components/SideBar.vue
> +<div class="">
тот же топик с пустым классом

2022-01-22 06:08 UTC, sashafromlibertalia commented on src/store/enums/buttonToAuth-data-enums.js
> +});
По-моему это оверинжиниринг..

2022-01-22 13:10 UTC, Aleksey-Levin commented on src/pages/Main.vue
> +  <div class=""></div>
Ну это просто, чтобы там что-то было в компоненте, а то он не запустится же без всего

2022-01-22 15:32 UTC, sashafromlibertalia commented on src/pages/Main.vue
> +  <div class=""></div>
ну кто мешает просто пустой div сделать?

2022-01-25 19:08 UTC, sashafromlibertalia requested changes

2022-01-25 19:08 UTC, sashafromlibertalia commented on src/assets/styles/components/ButtonToAuth.scss
> +  border-radius: 0.5vw;
я бы не рисковал и оставил в пикселях, да

2022-01-25 19:08 UTC, sashafromlibertalia commented on src/components/ButtonToAuth.vue
>  </template>
Мне кажется, что кнопку авторизации можно не выносить в отдельную компоненту. Она у нас явно будет использоваться в одном месте, а так больше зависимостей создаешь и потенциальных проблем

2022-01-25 19:08 UTC, sashafromlibertalia commented on src/pages/Auth.vue
> +      }
Что мешало просто сделать ```checkboxState```? или просто ```state```

2022-01-25 19:14 UTC, sashafromlibertalia commented
щас запустил демку - не оч круто в плане UX, что у тебя закрашен чекбокс, сделай его серым, пожалуйста
![Снимок экрана 2022-01-25 в 22 14 23](https://user-images.githubusercontent.com/36822207/151043716-1569b510-157f-413b-af41-c59996d47732.png)

2022-01-26 11:02 UTC, Aleksey-Levin commented on src/assets/styles/components/ButtonToAuth.scss
> +  border-radius: 0.5vw;
Если оно будет в пикселях, то при уменьшении экрана оно будет закругляться сильнее, чем было изначально

2022-01-26 11:40 UTC, sashafromlibertalia commented on src/assets/styles/components/ButtonToAuth.scss
> +  border-radius: 0.5vw;
ну это не особо критично, нам адаптивность на мобилках не особо нужна, я думаю. Ладно, оставь так

2022-01-26 11:42 UTC, sashafromlibertalia approved these changes

2022-01-26 11:42 UTC, sashafromlibertalia commented
Вроде как ты собираешься убрать путь `/main`, жду обнову с ним и можно уже ждать обнову с бека и делать рабочий прототип :)

2022-01-26 11:50 UTC, Aleksey-Levin commented
Есс, оно в процессе

2022-01-26 11:56 UTC, merged