Header bar
dev-sect/ScheduleDevelopmentKit-frontend pull request #13
Opened 2022-01-20 12:05 UTC by Aleksey-Levin

2022-01-20 13:40 UTC, sashafromlibertalia requested changes

2022-01-20 13:40 UTC, sashafromlibertalia commented on src/assets/styles/base/_normalize.scss
> +    cursor: default;
Курсор и так изначально default, можно эту строчку не писать

2022-01-20 13:40 UTC, sashafromlibertalia commented on src/App.vue
> +  <router-view></router-view>
Респект, но я бы сделал так - у нас будет отдельно компонент сайдбара и класс-обертка для router-view. Чтобы содержимое у нас менялось в зависимости от URL, а сайдбар всегда статичен был

2022-01-20 13:40 UTC, sashafromlibertalia commented on src/components/HeaderBar.vue
> +  },
а это что?

2022-01-20 13:40 UTC, sashafromlibertalia commented on src/components/PagesLayout.vue
> +  }
Так не надо делать, можно в настройках роутера указать, что по такому-то пути будет открываться конкретный компонент

2022-01-20 13:40 UTC, sashafromlibertalia commented on src/components/PagesLayout.vue
> +  </div>
а, ты вынес мое предложение в отдельный компонент. Ну хз, все же лучше это в App.vue добавить, так логичнее, чем делать новый компонент который особо и не нужен

2022-01-20 13:40 UTC, sashafromlibertalia commented on src/components/SidebarButton.vue
> +    }
выглядит как computed

2022-01-20 13:40 UTC, sashafromlibertalia commented on src/components/SidebarButton.vue
> +    },
советую писать просто 
```js
classObject() {

}
```

2022-01-20 13:40 UTC, sashafromlibertalia commented on src/router/index.js
> +                path: 'main',
```js
path: '/main'
```
и так для всего

2022-01-20 13:40 UTC, sashafromlibertalia commented on src/store/enums/sideBarButton-data-enums.js
> +    'item': '/item',
точно нельзя ключи сделать не строкой?

2022-01-21 13:48 UTC, Aleksey-Levin commented on src/components/HeaderBar.vue
> +  },
Ну это чтобы там прописывался путь адекватный 
![image](https://user-images.githubusercontent.com/66261148/150537833-15d8cb72-37f2-405e-b4c5-79e79794478c.png)
Как вот тут

2022-01-21 13:50 UTC, Aleksey-Levin commented on src/components/SidebarButton.vue
> +    }
а ой да, случайно

2022-01-21 13:51 UTC, Aleksey-Levin commented on src/store/enums/sideBarButton-data-enums.js
> +    'item': '/item',
а для чего?

2022-01-21 14:19 UTC, sashafromlibertalia commented on src/store/enums/sideBarButton-data-enums.js
> +    'item': '/item',
Обычно ключи объекта не записывают строкой, просто пожелания по кодстайлу

2022-01-21 14:19 UTC, sashafromlibertalia commented on src/components/HeaderBar.vue
> +  },
а, окей

2022-01-22 06:03 UTC, sashafromlibertalia requested changes

2022-01-22 06:03 UTC, sashafromlibertalia commented on src/router/index.js
>                  component: Main,
Я сегодня злой, стоит убрать путь /main, когда простой слеш по факту имеет тот же смысл, а так все ок

2022-01-22 13:06 UTC, Aleksey-Levin commented on src/router/index.js
>                  component: Main,
Я так и делал, но вот из-за этого:
![image](https://user-images.githubusercontent.com/66261148/150639717-23eb684a-7e96-4510-ae77-e033a5c4167f.png)


Я пытался сделать с пустым слэшом, но там треш контент выходил, спустя 2 часа мучений я ничего в итоге не сделал

2022-01-22 15:34 UTC, sashafromlibertalia commented on src/router/index.js
>                  component: Main,
почитай [это](https://router.vuejs.org/ru/guide/advanced/meta.html) и попробуй все же сделать так, как я предлагаю, так правда будет лучше

2022-01-26 12:25 UTC, sashafromlibertalia requested changes

2022-01-26 12:25 UTC, sashafromlibertalia commented on src/components/HeaderBar.vue
> +      return this.$route.matched.map(item=>{return item.meta.name}).join(' / ')
```js
.map(item=> item.meta.name)
```
А еще лучше стараться, где возможно, в колбеках не использовать `item` - слишком абстрактно и неясно, что ты мапишь

2022-01-26 12:25 UTC, sashafromlibertalia commented on src/pages/Main.vue
>  <div class="">
ну убери класс((((

2022-01-26 12:25 UTC, sashafromlibertalia commented on src/router/index.js
> +    }
Кажется, если это что-то связанное с авторизацией, то надо кидать на страницу логина. Убери это пока, я покажу как грамотно это оформить

2022-01-26 15:20 UTC, sashafromlibertalia approved these changes

2022-01-26 15:20 UTC, sashafromlibertalia commented
Пофикси конфликты и мержи в мастер

2022-01-28 13:29 UTC, merged