feat: teacher-card
dev-sect/ScheduleDevelopmentKit-frontend pull request #2
Opened 2021-11-18 18:55 UTC by dima-prezhentsov

2021-11-18 18:57 UTC, dima-prezhentsov commented
забыл иконки допилить

2021-11-18 19:02 UTC, sashafromlibertalia requested changes

2021-11-18 19:02 UTC, sashafromlibertalia commented on src/assets/styles/components/teacher-card.scss
> +  height: 120px;
Не рекомендую делать кнопки в пикселях, адаптивности не будет. Смотри в сторону rem

2021-11-18 19:02 UTC, sashafromlibertalia commented on src/assets/styles/components/teacher-card.scss
> +  border: 2px solid #F3F3F3;
Вроде бы цвет границы я выносил в переменную, глянь пж

2021-11-18 19:02 UTC, sashafromlibertalia commented on src/components/TeacherCard.vue
> +      teacherInfo: [308373, "mayatin@itmo.ru", "+7 999 999 99 99"]
Неплохо, но я бы сделал один объект, который хранит в себе всю инфу. Обращение по полям объекта будет читабельнее

2021-11-18 19:02 UTC, sashafromlibertalia commented on src/components/TeacherCard.vue
> +        <li class="info-row" v-for="info in teacherInfo" :key="info">{{ info }}</li>
Итерацию можно сделать вот так:
```js
(info, index) in teacherInfo
```
Индекс закинешь в виде ключа и будет сказка

2021-11-18 19:02 UTC, sashafromlibertalia commented on src/assets/styles/components/teacher-card.scss
> +    margin-bottom: 8px;
тот же топик с адаптивностью для маржи

2021-11-18 21:45 UTC, dima-prezhentsov commented on src/assets/styles/components/teacher-card.scss
> +  height: 120px;
rem это ведь размер относительный. Мне надо на глаз подбирать его? Просто я сначала вроде попытался, но мне все хотелось сделать точь в точь с размерами в макете

2021-11-19 10:06 UTC, sashafromlibertalia commented on src/assets/styles/components/teacher-card.scss
> +  height: 120px;
ну вот ты в пикселях подогнал его, сделай также через REM/иные адаптивные единицы. Мем в том, что мы без всех компонентов не узнаем, как оно в реале будет смотреться. Если что - переделаем, не проблема

P.S. - когда будешь заливать правки, жми на `resolve conversation` тех пунктов, которые ты починил

2021-11-19 10:09 UTC, dima-prezhentsov commented on src/assets/styles/components/teacher-card.scss
> +  height: 120px;
В том и дело что я в пикселях не подгонял а взял из фигмы) Ну в общем хорошо, я понял, подгоню через rem

2021-11-20 06:47 UTC, iskander-faggod commented on src/assets/styles/components/teacher-card.scss
> +  height: 120px;
адаптивность можно получить и с помощью флексов, оставив пиксельные значения
как будто нам не очень хочется, чтобы какой-то компонент менял свой размер

2021-11-20 06:47 UTC, iskander-faggod commented on src/components/TeacherCard.vue
> +        <li class="info-row" v-for="info in teacherInfo" :key="info">{{ info }}</li>
вью хорош

2021-11-20 07:05 UTC, sashafromlibertalia commented on src/assets/styles/components/teacher-card.scss
> +  height: 120px;
Вообще нужно 👀

2021-11-21 18:25 UTC, sashafromlibertalia requested changes
В целом ок, нам все равно потом придется прокидывать данные преподавателя через свойства, так что пока сойдет

2021-11-21 18:25 UTC, sashafromlibertalia commented on src/components/TeacherCard.vue
> +          phoneNumber: { data: "+7 999 999 99 99", icon: require("../icons/phoneNumber.svg") }
Форматирование оформи

2021-11-21 18:25 UTC, sashafromlibertalia commented on src/components/TeacherCard.vue
> +  <div class="teacher-card" v-on:click="goToTeacher">
@click

2021-11-22 10:30 UTC, dima-prezhentsov commented on src/components/TeacherCard.vue
> +          phoneNumber: { data: "+7 999 999 99 99", icon: require("../icons/phoneNumber.svg") }
Не понял

2021-11-22 11:52 UTC, sashafromlibertalia commented on src/components/TeacherCard.vue
> +          phoneNumber: { data: "+7 999 999 99 99", icon: require("../icons/phoneNumber.svg") }
ну, чтобы объект не был инлайновым, каждое поле на новой строчке

2021-11-22 11:53 UTC, sashafromlibertalia requested changes

2021-11-22 11:53 UTC, sashafromlibertalia commented on src/components/TeacherCard.vue
> +  <div class="teacher-card" @:click="goToTeacher">
без двоеточия :))
```html
<div class="teacher-card" @click="goToTeacher">
```

2021-11-22 11:54 UTC, sashafromlibertalia commented
Чтобы пофиксить конфликты, локально у себя пропиши `git pull`, должно помочь

2021-11-22 11:56 UTC, sashafromlibertalia approved these changes

2021-11-22 11:58 UTC, dima-prezhentsov commented on src/components/TeacherCard.vue
> +          phoneNumber: { data: "+7 999 999 99 99", icon: require("../icons/phoneNumber.svg") }
А, сек

2021-11-22 13:49 UTC, closed without merging