Main page
dev-sect/ScheduleDevelopmentKit-frontend pull request #20
Opened 2022-02-03 23:45 UTC by Aleksey-Levin

2022-02-04 12:13 UTC, sashafromlibertalia requested changes
Ура, блядский ковид меня немного отпустил и я частично жив!

Этот отступ справа вообще не оч, если честно, тут не нужен Флекс.
<img width="755" alt="Снимок экрана 2022-02-04 в 15 07 05" src="https://user-images.githubusercontent.com/36822207/152526422-b58a6baa-5075-4d7c-b0b5-202a3f135ead.png">

Идея вообще была такой, чтобы мы для всего содержимого использовали padding, чтобы у нас по умолчанию были красивые отступы на любой странице, тогда не пришлось бы такие фокусы исполнять. Тогда и смысла в марже для сайдбара не будет

.pagesLayout_contentRight - в этот класс добавь паддинг, он тогда для любого пути будет добавлять отступ, что нам в принципе и нужно :) 

Еще мне не очень нравится как у нас адаптивность себя ведет, надо будет что-то подумать с этим, по факту у нас не должно быть такого сильного сужения, а просто карточки должны в столбик раскладываться без особых проблем. Потенциальное решение - шрифты, где надо, надо будет перевести в rem, либо писать медиа запросы

<img width="608" alt="Снимок экрана 2022-02-04 в 15 11 55" src="https://user-images.githubusercontent.com/36822207/152526988-235c4d51-7f90-427e-9c7c-8d79fd14c00f.png">

2022-02-04 12:13 UTC, sashafromlibertalia commented on src/pages/Main.vue
> +      otherContentCards: ['Export', 'Import', 'ImportFromISU']
Вынеси их в `computed`

2022-02-04 12:13 UTC, sashafromlibertalia commented on src/components/SideBar.vue
> +}
Мне чот не оч нравится как выглядит сайдбар щас, вот причины: 
1. маржа справа тут не нужна, в комментарии напишу почему
2. было бы хорошо наверно через класс
```css
.sidebar_content
```
добавить отступ сверху, чтобы на макет было похоже. Либо контенту дать где-то 80% (навскидку) высоты от  контейнера, выравнять его по центру, а содержимое отображать через justify-content: flex-start; flex-wrap: wrap; flex-direction: column
Второй вариант кажется хорошим

2022-02-04 13:43 UTC, Aleksey-Levin commented on src/components/SideBar.vue
> +}
![image](https://user-images.githubusercontent.com/66261148/152538883-b67741f5-c1e4-40b9-b98e-079e537441d3.png)
Как-то грустно без маржы справа, не?

2022-02-04 13:50 UTC, sashafromlibertalia commented on src/components/SideBar.vue
> +}
А я тебе в основном комментарии написал, как это фиксануть :)

2022-02-04 14:14 UTC, Aleksey-Levin commented
> 

выздоравливай 😔
![image](https://user-images.githubusercontent.com/66261148/152543724-c696bcf8-2456-4fc9-9cc4-b19011864757.png)
вот так гуд?

2022-02-04 14:19 UTC, Aleksey-Levin commented on src/pages/Main.vue
> +      otherContentCards: ['Export', 'Import', 'ImportFromISU']
Так их же просто v-for перебирает, а через компутед как-то запарно делать... ну то есть надо же что-то передавать будет функции на основе чего она будет возвращать нужный тип карточки

2022-02-04 14:27 UTC, Aleksey-Levin commented on src/components/SideBar.vue
> +}
> А я тебе в основном комментарии написал, как это фиксануть :)

я ниже отправил скриншотик на оценочку

2022-02-04 14:33 UTC, sashafromlibertalia commented on src/pages/Main.vue
> +      otherContentCards: ['Export', 'Import', 'ImportFromISU']
не вижу проблемы сделать 3 функции в computed, которые просто возвращают нужный массив, а сейчас при желании твою дату можно модифицировать и все сломается

2022-02-04 14:34 UTC, sashafromlibertalia commented
Спасибо 🥺
Да, вполне

2022-02-04 18:30 UTC, sashafromlibertalia requested changes

2022-02-04 18:30 UTC, sashafromlibertalia commented on src/App.vue
> +  padding-left: 3vw;
Сделай общий паддинг, а не только слева, сверху/снизу поменьше только

2022-02-04 18:30 UTC, sashafromlibertalia commented on src/App.vue
> +  padding-left: 3vw;
а то у тебя все равно там Флекс торчит

2022-02-05 19:44 UTC, sashafromlibertalia requested changes

2022-02-05 19:44 UTC, sashafromlibertalia commented on src/assets/styles/components/quick-action.scss
> +    height: 120px;
а че так

2022-02-05 19:45 UTC, sashafromlibertalia commented
Я не понимаю, почему ты уже трижды забиваешь на мою просьбу убрать боковой отступ, поэтому сразу говорю, как надо:
```css
.pagesLayout {
    display: grid;
    grid-template-columns: 1fr 1fr;
}
```

2022-02-07 17:56 UTC, sashafromlibertalia approved these changes
За гриды мое почтение

2022-02-07 17:56 UTC, sashafromlibertalia commented
фикси конфликты и мержи

2022-02-07 17:57 UTC, Aleksey-Levin commented
айм соу сорри за такое долгое исправление, там просто были 3 дня путешествий

2022-02-07 18:12 UTC, merged