feat: initial commit for EditComponent
dev-sect/ScheduleDevelopmentKit-frontend pull request #22
Opened 2022-02-08 15:25 UTC by dima-prezhentsov

Это первая версия, так как я костыльнул там немного.
Суть в том что мне нужно изменить ширину инпутов имени и отчества. А так как я изначально хотел переиспользовать уже готовую компоненту ввода, то столкнулся с проблемой, что стили для них лежат в mixin и я не могу в нем ничего менять (так как они применятся ко всем Input). 
Через :style я пробовал, но он применяет стили ко всей компоненте в целом, а мне нужно только изменить ширину тега <input> в ней

2022-02-08 15:28 UTC, sashafromlibertalia requested changes

2022-02-08 15:28 UTC, sashafromlibertalia commented on src/components/Edit.vue
> +    padding: 1vw 2vw;
а че в отдельный файл не вынес

2022-02-08 15:29 UTC, sashafromlibertalia commented
Сделай отступ между именем и отчеством чуть больше

2022-02-08 15:30 UTC, dima-prezhentsov commented on src/components/Edit.vue
> +    padding: 1vw 2vw;
Та я пока не стал, потому что не окончательная версия

2022-02-08 15:31 UTC, sashafromlibertalia requested changes

2022-02-08 15:31 UTC, sashafromlibertalia commented on src/components/Edit.vue
> +  </div>
Вопрос наверно глупый, а почему у тебя ФИО лежит в Edit?

2022-02-08 15:32 UTC, sashafromlibertalia commented on src/components/Edit.vue
> +    padding: 1vw 2vw;
а ок

2022-02-08 15:32 UTC, sashafromlibertalia commented on src/components/Edit.vue
> +  </div>
видимо та же причина

2022-02-08 15:32 UTC, dima-prezhentsov commented on src/components/Edit.vue
> +  </div>
Немного не понял

2022-02-08 15:36 UTC, sashafromlibertalia commented on src/components/Edit.vue
> +  </div>
ну компонента Edit, а код для ФИО

2022-02-08 15:38 UTC, dima-prezhentsov commented on src/components/Edit.vue
> +  </div>
![image](https://user-images.githubusercontent.com/70948858/153021197-8b0ab678-fa3c-4575-af75-053d58b14a85.png)
так а я в issues увидел скрин этой компоненты и подумал что это она

2022-02-08 15:44 UTC, sashafromlibertalia commented on src/components/Edit.vue
> +  </div>
речь про кружочек с карандашом была)))))) Он же в разных местах будет сидеть

2022-02-08 15:46 UTC, dima-prezhentsov commented on src/components/Edit.vue
> +  </div>
Ааааа, только его надо было?)

2022-02-08 15:47 UTC, sashafromlibertalia commented on src/components/Edit.vue
> +  </div>
да)0

2022-02-08 15:48 UTC, sashafromlibertalia commented on src/components/Edit.vue
> +  </div>
ну зато чуть облегчил жизнь @Aleksey-Levin

2022-02-08 15:49 UTC, dima-prezhentsov commented on src/components/Edit.vue
> +  </div>
упс) Щас тогда ФИО в другую ветку залью. А в этой переделаю

2022-02-08 15:49 UTC, dima-prezhentsov commented on src/components/Edit.vue
> +  </div>
FIO Compnonent валидный нейминг?

2022-02-08 15:50 UTC, sashafromlibertalia commented on src/components/Edit.vue
> +  </div>
FullNameInput

2022-02-08 16:22 UTC, Aleksey-Levin commented
Так я же заливал изменения Инпута для ФИО

2022-02-08 16:48 UTC, sashafromlibertalia requested changes

2022-02-08 16:48 UTC, sashafromlibertalia commented on src/components/Edit.vue
> +  <img class="edit-btn" :src="icon" alt="edit" @click="Click">
а почему не <span>?

2022-02-08 16:48 UTC, sashafromlibertalia commented on src/components/Edit.vue
> +      icon: require("../assets/icons/Edit/edit.svg")
в computed

2022-02-08 16:48 UTC, sashafromlibertalia commented on src/components/Edit.vue
> +    }
1. С маленькой буквы
2. [emit](https://ru.vuejs.org/v2/guide/components-custom-events.html). Событие - change, например

2022-02-13 19:14 UTC, sashafromlibertalia approved these changes

2022-02-13 19:14 UTC, sashafromlibertalia commented on src/components/Edit.vue
> +      }
А зачем ДАТУ перенес в компьютед? Сделай просто computed property c названием icon()

2022-02-13 19:14 UTC, sashafromlibertalia commented on src/components/Edit.vue
> +  <span><img class="edit-btn" :src="data.icon" alt="edit" @click="$emit('change')"></span>
считается, что делать инлайновые функции не оч затея, сделай метод и вызывай его в верстке.

2022-02-13 19:15 UTC, sashafromlibertalia commented
блять кнопку перепутал((((

2022-02-13 19:15 UTC, sashafromlibertalia requested changes
ну ты понял

2022-02-13 19:16 UTC, dima-prezhentsov commented on src/components/Edit.vue
> +      }
Я просто не понял что конкретно нужно сделать)

2022-02-13 19:17 UTC, dima-prezhentsov commented on src/components/Edit.vue
> +  <span><img class="edit-btn" :src="data.icon" alt="edit" @click="$emit('change')"></span>
Окей

2022-02-13 19:18 UTC, sashafromlibertalia commented on src/components/Edit.vue
> +      }
```js
computed: { 
    icon() {
          return require("../assets/icons/Edit/edit.svg")
    }
}
```

2022-02-13 19:19 UTC, dima-prezhentsov commented on src/components/Edit.vue
> +      }
А, затупил

2022-02-13 19:20 UTC, sashafromlibertalia commented on src/components/Edit.vue
> +      }
бывает

2022-02-14 11:02 UTC, sashafromlibertalia approved these changes
Верни исходную код в App.vue, а потом мержи

2022-02-14 11:03 UTC, sashafromlibertalia commented
а, уже, я понял

2022-02-14 11:04 UTC, merged