initial commit
dev-sect/ScheduleDevelopmentKit-frontend pull request #23
Opened 2022-02-17 07:50 UTC by Aleksey-Levin

2022-02-17 14:07 UTC, sashafromlibertalia requested changes
Вроде бы все проверил, единственное, почему-то ошибка имеет маленький размер шрифта, вроде же все ок было. Глянешь?
<img width="408" alt="Снимок экрана 2022-02-17 в 17 07 00" src="https://user-images.githubusercontent.com/36822207/154498130-5431f295-de74-4a1a-96d7-5b74d2913df5.png">

2022-02-17 14:07 UTC, sashafromlibertalia commented on src/router/index.js
> +                path: '/createTeacher',
не советую писать роуты в camelcase
сделай /create/teacher

2022-02-17 14:07 UTC, sashafromlibertalia commented on src/store/modules/quickActions.js
> +            path: '/createTeacher'
если тут есть путь, почему бы его не переиспользовать

2022-02-17 14:07 UTC, sashafromlibertalia commented on src/pages/Main.vue
> +    <router-view/>
а зачем тут роутер-вью?

2022-02-17 14:07 UTC, sashafromlibertalia commented on src/pages/Main.vue
> +    <div class="mainPage" v-if="$route.path=='/'">
зачем это  условие

2022-02-17 14:07 UTC, sashafromlibertalia commented on src/pages/CreateTeacher.vue
> +        <Input type-obj="PATRONYMIC"/>
а почему стиль названия типа отличается? Вообще, есть ощущение, что лучше в computed добавить объект который типы инпутов хранит, чтобы конкретный тип вставить и не бояться, что напишешь его как-то не так

2022-02-17 14:07 UTC, sashafromlibertalia commented on src/assets/styles/components/MainPage.scss
Шрифты у заголовков чот огромные, сделай поменьше, в дизайне они меньше

2022-02-17 14:07 UTC, sashafromlibertalia commented on src/pages/Main.vue
> +          <QuickAction v-for="card in viewContentCards" :key="card" :type="card" class = "quickAction"/>
Не пиши присвоение классов с пробелами как в нормальных языках)))

2022-02-17 14:07 UTC, sashafromlibertalia commented on src/pages/CreateTeacher.vue
> +    <button class = "save"> Сохранить </button>
тот же топик про пробелы, везде убери это

2022-02-17 14:07 UTC, sashafromlibertalia commented on src/pages/CreateTeacher.vue
> +  margin-top: 8em;
не советую так делать, закинь в единую маржу

2022-02-26 15:00 UTC, Aleksey-Levin commented on src/store/modules/quickActions.js
> +            path: '/createTeacher'
ты про icon?

2022-02-26 15:02 UTC, Aleksey-Levin commented on src/pages/Main.vue
> +    <router-view/>
Для контента помимо main :)
Да просто там вот этот путь, который в хэддере серым должен отображаться, получается делать только так(

2022-02-26 15:02 UTC, Aleksey-Levin commented on src/pages/Main.vue
> +    <div class="mainPage" v-if="$route.path=='/'">
опять же для пути

2022-02-26 15:02 UTC, sashafromlibertalia commented on src/pages/Main.vue
> +    <router-view/>
чот страшно. ты пробовал смотреть в сторону `this.$route`?

2022-02-26 15:03 UTC, sashafromlibertalia commented on src/store/modules/quickActions.js
> +            path: '/createTeacher'
про path

2022-02-26 15:03 UTC, Aleksey-Levin commented on src/pages/CreateTeacher.vue
> +        <Input type-obj="PATRONYMIC"/>
Потому что Input'ы различны по размеру и чтобы каждый из них контролить

2022-02-26 15:04 UTC, sashafromlibertalia commented on src/pages/Main.vue
> +    <div class="mainPage" v-if="$route.path=='/'">
Все равно оч странно, у тебя и так этот компонент отвечает за главную страницу, зачем еще этот иф херачить. Мб я уже забыл че тут такое

2022-02-26 15:05 UTC, sashafromlibertalia commented on src/pages/CreateTeacher.vue
> +        <Input type-obj="PATRONYMIC"/>
я про капс и pascalcase, как написание связано с этим?)

2022-02-26 15:09 UTC, sashafromlibertalia commented on src/pages/CreateTeacher.vue
> +        <Input type-obj="PATRONYMIC"/>
обманул, это camelcase

2022-02-26 15:14 UTC, Aleksey-Levin commented on src/store/modules/quickActions.js
> +            path: '/createTeacher'
так оно же уже отсюда и переиспользуется

2022-02-26 15:16 UTC, Aleksey-Levin commented on src/pages/Main.vue
> +    <router-view/>
Мы уже пытались в прошлых коммитах решить эту проблему, тип там я написал один вариант решения, ты сказал сделать через meta в роуте. Просто я не понимаю как это сделать ещё, если путь у главной страницы не будет через /main указан(

2022-02-26 15:16 UTC, Aleksey-Levin commented on src/pages/CreateTeacher.vue
> +        <Input type-obj="PATRONYMIC"/>
а ой, сейчас исправлю

2022-02-26 15:18 UTC, sashafromlibertalia commented on src/store/modules/quickActions.js
> +            path: '/createTeacher'
У тебя два перечисления содержат одно и то же значения, причем одно для переиспользования и задумывалось
![image](https://user-images.githubusercontent.com/36822207/155848501-0dd8bf45-f549-4287-9bcc-a5857f7c511a.png)

2022-02-26 15:19 UTC, sashafromlibertalia commented on src/pages/Main.vue
> +    <router-view/>
ладно, я потом есчо сам гляну и починю, щас не оч могу копаться и что-то посоветовать, оставляем

2022-02-26 16:51 UTC, sashafromlibertalia approved these changes

2022-02-26 16:51 UTC, sashafromlibertalia commented
мержи

2022-02-26 16:55 UTC, merged