feat: add input
dev-sect/ScheduleDevelopmentKit-frontend pull request #3
Opened 2021-11-21 13:25 UTC by Aleksey-Levin

2021-11-21 14:00 UTC, iskander-faggod commented on src/components/Input.vue
> +
убери отступ пожалуйста

2021-11-21 14:01 UTC, iskander-faggod commented on src/components/Input.vue
> +      console.log(this);
зачем нам твои this-ы на проде)

2021-11-21 14:18 UTC, sashafromlibertalia commented on src/components/Input.vue
> +
Где заголовок? :)

2021-11-21 14:27 UTC, Aleksey-Levin commented on src/components/Input.vue
> +      console.log(this);
Я случайно :)

2021-11-21 14:31 UTC, Aleksey-Levin commented on src/components/Input.vue
> +
В смысле после default?

2021-11-21 14:34 UTC, Aleksey-Levin commented on src/components/Input.vue
> +
Что такое заголовок ?:)

2021-11-21 14:35 UTC, sashafromlibertalia commented on src/components/Input.vue
> +
Нет, у тебя табуляция умерла

2021-11-21 14:36 UTC, sashafromlibertalia commented on src/components/Input.vue
> +
В макете был Хедер, а для ошибки была подпись под инпутом

2021-11-21 15:02 UTC, sashafromlibertalia requested changes

2021-11-21 15:02 UTC, sashafromlibertalia commented on src/components/Input.vue
>        }
Прокидывать в название класса тип инпута - не оч идея. Vue имеет такую штуку как `properties`, чтобы ты извне указывал конкретный тип инпута как-то так:
```js
<Input :type="password">
```

Как правильно прокидывать свойства можно найти в ноушне, я все ссылки оставил

2021-11-21 15:02 UTC, sashafromlibertalia commented on src/components/Input.vue
> +      v-on:click="setType"
**`@click`** вместо `v-on:click`

2021-11-21 15:02 UTC, sashafromlibertalia commented on src/components/Input.vue
> +      v-on:change="checkCorrectValue"
Также, как и с кликом

2021-11-21 15:02 UTC, sashafromlibertalia commented on src/components/Input.vue
>          this.type = 'text';
Есть проблемка - такой код нудно модифицировать (я про типы инпута).
Как бы я сделал - сделал отдельный [замороженный](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) объект (по факту - enum), который хранил бы в себе всевозможные типы инпутов, которые у нас будут.
Поскольку еще будешь тип передавать, не нужно будет устраивать пляски с классами

2021-11-21 15:02 UTC, sashafromlibertalia commented on src/components/Input.vue
> +      if (this.$el.classList.contains('e-mail')) {
Сразу перепиши под switch/case и смотри тип из свойства

2021-11-21 15:02 UTC, sashafromlibertalia commented on src/components/Input.vue
> -      v-on:click="setType">
Раз речь зашла про классы, можно динамически накидывать класс, который нам нужен:
```js
<input :class='{"password": this.type === Input.Types.Password, ...}'>
```

[Подробнее](https://vuejs.org/v2/guide/class-and-style.html#Object-Syntax)

2021-11-21 15:02 UTC, sashafromlibertalia commented on src/assets/styles/helpers/_variables.scss
> +$input-PlaceHolder-color: #ADADAD;
Я эту переменную выносил
**$text__default-color--gray**

2021-11-21 15:02 UTC, sashafromlibertalia commented on src/assets/styles/helpers/_variables.scss
>  $input-PlaceHolder-font:'Times New Roman';
Откуда тут взялся Романыч.....

2021-11-21 15:02 UTC, sashafromlibertalia commented on src/assets/styles/components/Input.scss
> +  outline-color: $input-borderColor-error;
**$item__state-background--error** - снова топик про цвет ошибки)

2021-11-21 15:02 UTC, sashafromlibertalia commented on src/assets/styles/helpers/_mixins.scss
>    background-color: #F3F3F3;
1. Зачем прокидывать ширину и высоту, когда можно это хранить в миксине сразу, у нас размер будет один. Вдруг что - переопределим внутри самого компонента
2. Background у меня тоже был вынесен в переменную: **$item__state-background--blur**

2021-11-21 15:02 UTC, sashafromlibertalia commented on src/assets/styles/helpers/_variables.scss
> +$input-borderColor-error: red;
Убрать

2021-11-21 15:05 UTC, sashafromlibertalia requested changes

2021-11-21 15:05 UTC, sashafromlibertalia commented on src/assets/styles/helpers/_mixins.scss
> +  border-radius: 12px;
border-radius я тоже выносил отдельно

2021-11-21 15:05 UTC, sashafromlibertalia commented on src/assets/styles/helpers/_variables.scss
> +$input-fontLine: 24px;
1. Умрем это поддерживать
2. Еще и пиксели, неадаптивно

Убрать

2021-11-21 15:05 UTC, sashafromlibertalia commented
Ставь метки "Resolve conversation", когда что-то починишь, пожалуйста 👉👈

2021-11-21 16:03 UTC, sashafromlibertalia commented
Еще забыл добавить пулреквест на доску, не делай так пж больше

2021-11-21 17:47 UTC, Aleksey-Levin commented on src/components/Input.vue
>        }
воот, я пытался такое найти, но видимо очень плохо искал

2021-11-21 17:47 UTC, Aleksey-Levin commented on src/assets/styles/helpers/_variables.scss
>  $input-PlaceHolder-font:'Times New Roman';
гуд квешион, видимо я забыл изменить :)

2021-12-04 11:15 UTC, sashafromlibertalia requested changes

2021-12-04 11:15 UTC, sashafromlibertalia commented on src/assets/styles/helpers/_mixins.scss
> +  width: 520px;
в пикселях не стоит писать ширину

2021-12-04 11:15 UTC, sashafromlibertalia commented on src/assets/styles/helpers/_mixins.scss
> +  height: 24px;
не смотрел еще верстку, но есть ощущение, что можно поставить автоматическую высоту, а подгоняться она будет через padding
Но если никак - тот же топик про пиксели

2021-12-04 11:15 UTC, sashafromlibertalia commented on src/components/Input.vue
> +  props: ['typeObj', 'headValue', 'ClassName', 'errorValue'],
Пропсы нужно объявлять как объекты с указанием типа, в идеале - с валидатором

2021-12-04 11:15 UTC, sashafromlibertalia commented on src/App.vue
> +    <Input placeholder="Ваш пароль" type-obj="password" head-value="Пароль" errorValue="Пароль должен содержать минимум 8 символов и одну цифру"/>
Placeholder и прочие штуки должны подгоняться в зависимости от типа инпута внутри самого компонента. Текст ошибки всегда будет один, и если в каком-то месте человек введет через свойства текст, то в другом месте уже другой человек этот текст не введет и все умрет - так не надо.
Валидируй в маунте, например

2021-12-04 11:15 UTC, sashafromlibertalia commented on src/assets/styles/components/Input.scss
> +}
Можно оформить вложенность классов:
```scss

// Рекомендуется делать не более 3 уровней вложенности
.input {
    &_error {
      &_text {
       //
       }
    }
}
```

2021-12-04 11:15 UTC, sashafromlibertalia commented on src/assets/styles/components/Input.scss
> +  font-family: $input-errorText-font;
Зачем сделал переменную для `font-family`, когда был готовый миксин

2021-12-04 11:15 UTC, sashafromlibertalia commented on src/assets/styles/helpers/_variables.scss
> +$input-PlaceHolder-font:'SF PRO Display';
Миксины на шрифт были :) Следовательно, смысла в этих переменных нету

2021-12-04 11:15 UTC, sashafromlibertalia commented on src/assets/styles/helpers/_variables.scss
> +$input-errorText-lineHeight:15px;
Забудь про пиксели
line-height тоже можно в принципе не трогать, поставив просто `auto` и все, не видел случаев чтобы это было большой проблемой

2021-12-04 11:15 UTC, sashafromlibertalia commented on src/components/Input.vue
> +      <p> {{headValue}} </p>
Семантическая верстка! Поставь `<h3>`, например

2021-12-04 11:15 UTC, sashafromlibertalia commented on src/components/Input.vue
> +        :class='{"password": this.typeObj === "password", "e-mail": this.typeObj === "e-mail"}'>
Я кстати подумал, что было бы неплохо вынести типы инпутов в отдельный enum, чтобы интересных кейсов не случилось. Гугли `Object.freeze`

2021-12-04 11:15 UTC, sashafromlibertalia commented on src/components/Input.vue
> +      }
попробуй в валидатор свойства прокинуть это
Ну и с использованием enum'а

2021-12-04 11:15 UTC, sashafromlibertalia commented on src/components/Input.vue
> +            this.$el.querySelector('.errorText').style.display = "none";
😳
`v-if`, не?

2021-12-05 20:37 UTC, sashafromlibertalia commented on src/components/Input.vue
> +      value: '',
не заметил сразу, поставь null

2022-01-07 04:37 UTC, Aleksey-Levin commented on src/assets/styles/helpers/_mixins.scss
> +  width: 520px;
> в пикселях не стоит писать ширину

Таки а как тут ещё? В процентах не написать, какие-нибудь rem, em тоже не подойдут. Паддингами, ну там тоже через пиксели получится

2022-01-07 10:53 UTC, Aleksey-Levin commented on src/assets/styles/helpers/_mixins.scss
> +  width: 520px;
> > в пикселях не стоит писать ширину
> 
> Таки а как тут ещё? В процентах не написать, какие-нибудь rem, em тоже не подойдут. Паддингами, ну там тоже через пиксели получится

а ну, через vw сделать?

2022-01-07 13:53 UTC, sashafromlibertalia commented on src/assets/styles/helpers/_mixins.scss
> +  width: 520px;
Почему rem/em не подойдут? Все равно придется потом через медиа запросы в случае чего подгонять размеры
А так да, можно и через vw

2022-01-09 15:02 UTC, sashafromlibertalia requested changes

2022-01-09 15:02 UTC, sashafromlibertalia commented on src/App.vue
> +    <Input type-obj="password" head-value="Пароль"/>
А зачем прокидывать заголовок в пропсы? В зависимости от типа компонент сам должен отрисовать тот текст, который нужно

2022-01-09 15:02 UTC, sashafromlibertalia commented on src/assets/styles/helpers/_variables.scss
>  $input-errorText-fontSize:12px;
в em/rem

2022-01-09 15:02 UTC, sashafromlibertalia commented on src/components/Input.vue
> +    Object.freeze(this.typeInput);
а это вообще зачем? 🤨

2022-01-09 15:02 UTC, sashafromlibertalia commented on src/components/Input.vue
> +      },
следует вынести в отдельный файл :) И фризить его в маунте не надо

2022-01-09 15:02 UTC, sashafromlibertalia commented on src/components/Input.vue
>            elemInput.classList.add('errorInput');
Когда ты работаешь с Vue, приколов с classList вообще быть не должно, ибо все делается через инструменты самого вью. Убрать

2022-01-09 15:02 UTC, sashafromlibertalia commented on src/components/Input.vue
> +        :class="[{errorInput:multipleTypeInput[this.typeObj]['regular'].test(this.value) == false}, typeInput[this.typeObj]]"
выглядит как нечто страшное, можно красиво обернуть в нечто такое:
```js
<div v-bind:class="classObject"></div>
data: {
  isActive: true,
  error: null
},
computed: {
  classObject: function () {
    return {
      active: this.isActive && !this.error,
      'text-danger': this.error && this.error.type === 'fatal'
    }
  }
}
```

[Источник](https://ru.vuejs.org/v2/guide/class-and-style.html#Использование-объектов)

2022-01-09 15:02 UTC, sashafromlibertalia commented on src/components/Input.vue
> +    typeObj: String,
Можно еще required добавить, а второе свойство убрать вовсе, ну я уже писал

2022-01-09 15:02 UTC, sashafromlibertalia commented on src/components/Input.vue
> +      },
и ключи лучше писать капсом по типу:
```js
const inputTypes = Object.freeze({
    PASSWORD: "password",
    // etc.
})
```

2022-01-09 15:04 UTC, Aleksey-Levin commented on src/components/Input.vue
> +    Object.freeze(this.typeInput);
ты попросил это сделать...

2022-01-09 15:05 UTC, Aleksey-Levin commented on src/components/Input.vue
> +    Object.freeze(this.typeInput);
"Я кстати подумал, что было бы неплохо вынести типы инпутов в отдельный enum, чтобы интересных кейсов не случилось. Гугли Object.freeze"

2022-01-09 15:08 UTC, sashafromlibertalia commented on src/components/Input.vue
> +    Object.freeze(this.typeInput);
ну я ниже написал как надо

2022-01-09 15:23 UTC, Aleksey-Levin commented on src/components/Input.vue
> +      },
> следует вынести в отдельный файл :) И фризить его в маунте не надо

Отдельный файл это типа создать файл.js и экспортировать оттуда объект?...

2022-01-09 15:33 UTC, sashafromlibertalia commented on src/components/Input.vue
> +      },
да

2022-01-09 15:33 UTC, sashafromlibertalia commented on src/components/Input.vue
> +      },
файл создать в `/store/enums/`

2022-01-09 16:42 UTC, sashafromlibertalia requested changes

2022-01-09 16:42 UTC, sashafromlibertalia commented on src/store/enums.js
> +    'E-MAIL': "e-mail",
Кто мешал сделать EMAIL?

2022-01-09 16:42 UTC, sashafromlibertalia commented on src/store/enums.js
> +export {inputTypes};
export default, чтобы импортировал без скобок

2022-01-09 16:42 UTC, sashafromlibertalia commented on src/components/Input.vue
> +        errorInput: this.multipleTypeInput[this.typeObj]['regular'].test(this.value) == false,
можно не приравнивать явно к false, а просто указать 
```js
!this.multipleTypeInput[this.typeObj]['regular'].test(this.value)
```

2022-01-09 16:43 UTC, sashafromlibertalia commented
В принципе если все это сделаешь, я больше не буду мучать))

2022-01-09 16:44 UTC, sashafromlibertalia commented
СТОЯТЬ, У МЕНЯ ПОЧЕМУ-ТО ЕЩЕ ОДНА ПРАВКА НЕ ЗАГРУЗИЛАСЬ

2022-01-09 16:47 UTC, sashafromlibertalia requested changes

2022-01-09 16:47 UTC, sashafromlibertalia commented on src/components/Input.vue
> +        }
Короче, я бы на твоем месте все эти штуки с валидацией и текстом вынес в computed. Почему? 
Беда в том, что твою регулярку, например, можно будет спокойно изменить где-то позже в коде, и все сломается.
А так - ты вынес отдельно валидацию в один computed метод, placeholder в другой, заголовок в третий.

Чтобы сделать хайпово без кучи switch/case, можно сделать так:
```js
// Don't ❌
const getColorByStatus = (status) => {
  switch (status) {
    case "success":
      return "green";
    case "failure":
      return "red";
    case "warning":
      return "yellow";
    case "loading":
    default:
      return "blue";
  }
};

// Do ✅
const statusColors = {
  success: "green",
  failure: "red",
  warning: "yellow",
  loading: "blue",
};

const getColorByStatus = (status) => statusColors[status] || "blue";
```
[Сурс](https://medium.com/geekculture/writing-clean-javascript-es6-edition-834e83abc746)

2022-01-09 16:54 UTC, sashafromlibertalia commented
Сверстано кстати круто, мне понравилось

2022-01-09 17:00 UTC, Aleksey-Levin commented on src/store/enums.js
> +export {inputTypes};
ну я просто так делал на случай, если вдруг этот файл ещё как-то юзать будут

2022-01-09 17:07 UTC, sashafromlibertalia commented on src/store/enums.js
> +export {inputTypes};
Будут скорее всего, ну и что...

2022-01-12 12:26 UTC, Aleksey-Levin commented on src/components/Input.vue
> +        }
Там треш какой-то получается(
_getRegular:{
      get:
         function (type){
           return this.regular[type]
      },
      set:function(){
        this.regular = {
        phone: /(\+7|8)[\s(]?(\d{3})[\s)]?(\d{3})[\s-]?(\d{2})[\s-]?(\d{2})/,
        email:/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
        password:/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/
        }
      }
    },_

Типа я делаю так, оно вообще не хочет воркать ,а писать объекты в data же бессмысленно, ибо это ничем не будет отличаться же

2022-01-12 12:27 UTC, sashafromlibertalia commented on src/components/Input.vue
> +        }
бля больно читать
Можешь в код обернуть?)

2022-01-12 12:34 UTC, Aleksey-Levin commented on src/components/Input.vue
> +        }
```
getRegular:{
      get:
          function (type){
            return this.regular[type]
      },
      set:function(){
        this.regular = {
        phone: /(\+7|8)[\s(]?(\d{3})[\s)]?(\d{3})[\s-]?(\d{2})[\s-]?(\d{2})/,
        email:/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
        password:/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/
        }
      }
    },
```

2022-01-12 12:40 UTC, sashafromlibertalia commented on src/components/Input.vue
> +        }
Вообще я хотел нечто вроде: 
```js
const regularObj = {
  phone: /(\+7|8)[\s(]?(\d{3})[\s)]?(\d{3})[\s-]?(\d{2})[\s-]?(\d{2})/,,
  // et.c
};

getRegular() {
     return regularObj[this.type] || null
}
```

2022-01-12 12:42 UTC, Aleksey-Levin commented on src/components/Input.vue
> +        }
А вот этот regularObj задавать в data()?

2022-01-12 12:45 UTC, sashafromlibertalia commented on src/components/Input.vue
> +        }
нет, думаю, что внутри скрипта просто. Вряд ли у нас будет нужда использовать этот энам где-то извне, зафризь его тоже. 
В дате ты хранишь данные, которые будут **модифицироваться**, чтобы потом, например, отправиться куда-то в сторону бекенда)

2022-01-12 16:40 UTC, sashafromlibertalia commented on src/components/Input.vue
> +    <div class="errorText" v-if = "getRegular(this.typeObj).test(this.value) === false"> {{getErrorMessage(this.typeObj)}}</div>
Опять явное приравнивание к false

2022-01-12 16:43 UTC, sashafromlibertalia requested changes

2022-01-12 16:43 UTC, sashafromlibertalia commented on src/store/enums.js
>  });
Заебись
Переименуй файлик в input-data-enums, например. `Enums` - это папка)

2022-01-13 08:28 UTC, sashafromlibertalia approved these changes

2022-01-13 10:26 UTC, merged