feat: add new component ButtonOfQuickAction
dev-sect/ScheduleDevelopmentKit-frontend pull request #4
Opened 2021-11-21 15:39 UTC by miht-sem

2021-11-21 15:59 UTC, sashafromlibertalia requested changes

2021-11-21 15:59 UTC, sashafromlibertalia commented on src/App.vue
> +    <ButtonOfQuickAction></ButtonOfQuickAction>
Я бы компонент назвал просто `QuickAction`. У нас вряд ли пока планируется что-то еще с похожей логикой

2021-11-21 15:59 UTC, sashafromlibertalia commented on src/App.vue
> +  <span>
div

2021-11-21 15:59 UTC, sashafromlibertalia commented on src/assets/styles/components/button-quick-action.scss
> +        border: 0.125rem solid #2B3442;
цвет границы есть в переменных. Там вроде тот же цвет, что и для текста

2021-11-21 15:59 UTC, sashafromlibertalia commented on src/assets/styles/components/button-quick-action.scss
> +//}
Почему это в комментарии и в пул реквесте в целом?

2021-11-21 15:59 UTC, sashafromlibertalia commented on src/components/ButtonOfQuickAction.vue
> +    name: "ButtonOfQuickAction",
QuickAction

2021-11-21 15:59 UTC, sashafromlibertalia commented on src/components/ButtonToAddTeacher.vue
> +    <div class='button-add-teacher' @click="showAlert">{{ textButton }}</div>
А тут как раз кнопку лучше б оставил)

2021-11-21 15:59 UTC, sashafromlibertalia commented on src/components/ButtonOfQuickAction.vue
> +    },
Вот тут и начнется веселье. Этот компонент будет переиспользоваться для кучи разных действий, в макете видно. У всех будет разный текст/фон/иконки/логика/etc. Дата тут не подойдет
Я рекомендую сделать извне [замороженный](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) объект, который будет хранить в себе описание всех быстрых действий, будет не оч запарно поддерживать и модифицировать этот код.  
Передавай через `props` тип используемой кнопки с помощью этого объекта и валидируй отображение уже в самом компоненте. Как грамотно объявить свойства есть в ноушне, ну и в целом это нормально гуглится



Вот пример, можно додумать как допилить для нашей ситуации:
```js
const Colors = Object.freeze({
  RED:   { name: "red", hex: "#f00" },
  BLUE:  { name: "blue", hex: "#00f" },
  GREEN: { name: "green", hex: "#0f0" }
});
```

2021-11-21 16:03 UTC, miht-sem commented on src/assets/styles/components/button-quick-action.scss
> +//}
Ой...

2021-11-21 20:36 UTC, sashafromlibertalia requested changes

2021-11-21 20:36 UTC, sashafromlibertalia commented on src/App.vue
> +    <QuickAction type="Timetable"></QuickAction>
:type

2021-11-21 23:50 UTC, miht-sem commented on src/App.vue
> +    <QuickAction type="Timetable"></QuickAction>
Там вроде просто type должен быть

2021-11-22 07:17 UTC, sashafromlibertalia approved these changes

2021-11-22 07:18 UTC, merged